export type LocalizedFormatSymbols =
  | "LT"
  | "LTS"
  | "L"
  | "LL"
  | "LLL"
  | "LLLL"
  | "l"
  | "ll"
  | "lll"
  | "llll";

export type LocalizedFormat<T extends string> = T extends "LT"
  ? "h:mm A"
  : T extends "LTS"
  ? "h:mm:ss A"
  : T extends "L"
  ? "MM/DD/YYYY"
  : T extends "LL"
  ? "MMMM D, YYYY"
  : T extends "LLL"
  ? "MMMM D, YYYY h:mm A"
  : T extends "LLLL"
  ? "dddd, MMMM D, YYYY h:mm A"
  : T extends "l"
  ? "M/D/YYYY"
  : T extends "ll"
  ? "MMM D, YYYY"
  : T extends "lll"
  ? "MMM D, YYYY h:mm A"
  : T extends "llll"
  ? "ddd, MMM D, YYYY h:mm A"
  : never;
